name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up C++ compiler
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        echo "Running test for even number"
        echo "2" | ./build/even_or_odd

        echo "Running test for odd number"
        echo "3" | ./build/even_or_odd
